#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
hr = 0
while (( hr <= 12 ))
do
	echo "Hour: $hr"
	(( hr++ ))
	min=0
	while (( min < 59 ))
	do
		(( min++ ))
		echo $min
	done
done